buttercms/blog_blueprint.py
from butter_cms import ButterCMS
from flask import Blueprint, render_template, abort, Response
import os

blog = Blueprint('blog', __name__, template_folder='templates/blog')


auth_token = os.getenv("BUTTERCMS_API_TOKEN")
client = ButterCMS(auth_token)


@blog.route('/')
@blog.route('/page/<int:page>')
def home(page=1):
    response = client.posts.all({'page': 1, 'page_size': 10})
    posts = response['data']
    next_page = response['meta']['next_page']
    previous_page = response['meta']['previous_page']
    return render_template(
        'blog.html',
        posts=posts,
        next_page=next_page,
        previous_page=previous_page
    )


@blog.route('/<slug>')
def show_post(slug):
    response = client.posts.get(slug)
    try:
        post = response['data']
    except KeyError:
        # Post was not found
        abort(404)
    return render_template('post.html', post=post)


@blog.route('/author/<author_slug>')
def show_author(author_slug):
    response = client.authors.get(author_slug, {'include': 'recent_posts'})

    try:
        author = response['data']
    except KeyError:
        # Author was not found
        abort(404)
    return render_template('author.html', author=author)


@blog.route('/category/<category_slug>')
def show_category(category_slug):
    response = client.categories.get(
        category_slug,
        {'include': 'recent_posts'}
    )
    try:
        category = response['data']
    except KeyError:
        # category was not found
        abort(404)
    return render_template('category.html', category=category)


@blog.route('/rss')
def rss_feed():
    response = client.feeds.get('rss')
    return Response(response['data'], mimetype='text/xml')


@blog.route('/atom')
def atom_feed():
    response = client.feeds.get('atom')
    return Response(response['data'], mimetype='text/xml')


@blog.route('/sitemap.xml')
def sitemap():
    response = client.feeds.get('sitemap')
    return Response(response['data'], mimetype='text/xml')

buttercms/templates/blog/author.html
{% extends "blog.html" %}

{% block content %}
<a href="{{ url_for('blog.home') }}">Blog Home</a>
<h3>{{ author.first_name }} {{ author.last_name }} Recent Posts</h3>

{% for post in author.recent_posts %}
<div><a href="{{ url_for('blog.show_post', slug=post.slug) }}">{{ post.title }}</a></div>
{% endfor %}

{% endblock %}

buttercms/templates/blog/blog.html
{% block head %}
{% block title %} Flask blog powered by ButterCMS {% endblock %}
{% endblock %}

{% block content %}
<div class="container">
  <h1>ButterCMS &lt;3 Flask</h1>
  {% for post in posts %}
  <div><a href="{{ url_for('blog.show_post', slug=post.slug) }}">{{ post.title }}</a></div>
  {% endfor %}

  <!-- Pagination links -->
  <hr>
  <div>
    {% if previous_page %}
    <a href="{{ url_for('blog.home', page=previous_page) }}">Prev</a>
    {% endif %}

    {% if next_page %}
    <a href="{{ url_for('blog.home', page=next_page) }}">Next</a>
    {% endif %}
  </div>
</div>
{% endblock %}

buttercms/templates/blog/category.html
{% extends "blog.html" %}

{% block content %}
<a href="{{ url_for('blog.home') }}">Blog Home</a>
<h3>Recent posts in {{ category.name }}</h3>

{% for post in category.recent_posts %}
<div><a href="{{ url_for('blog.show_post', slug=post.slug) }}">{{ post.title }}</a></div>
{% endfor %}
{% endblock %}

buttercms/templates/blog/post.html
{% extends "blog.html" %}

{% block content %}
<a href="{{ url_for('blog.home') }}">Blog Home</a>
<h3>{{ post.title }}</h3>
<h5>By <a href="{{ url_for('blog.show_author', author_slug=post.author.slug) }}">{{ post.author.first_name }} {{ post.author.last_name }}</a></h5>
<h6>Posted in 
{% for category in post.categories %}
<a href="{{ url_for('blog.show_category', category_slug=category.slug) }}">{{category.name}}</a>
{% endfor %}
</h6>

<p>{{ post.body|safe }}</p>

<!--
// For sharing, we recommend https://www.addthis.com/get/sharing or https://sumome.com/app/share
-->

<!--
// For commenting, we recommend https://disqus.com/
// Create a Disqus account and paste your snippet below
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'XXXXXXXX';
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
-->
{% endblock %}